config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :attendances
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, presence: true
    validates :duration, presence: true, numericality: { greater_than: 0 }
    validate :devisible_by_5
    validates :title, presence: true, length: { minimum: 5, maximum: 140 }
    validates :description, presence: true, length: { minimum: 20, maximum: 1000 }
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0}
    validates :location, presence: true
    validate :start_date_cannot_be_in_the_past
    has_many :attendances
    has_many :users, through: :attendances
    def start_date_cannot_be_in_the_past
        if start_date.present? && start_date < Date.today
            errors.add(:start_date, "can't be in the past")
        end
    end
    def devisible_by_5
        if duration.present? && duration % 5 != 0
            errors.add(:duration, "must be a multiple of 5")
        end
    end 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :user_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>" class="card-block">
  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= event.duration %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<div class="hero" style="background-image: url(<%= asset_path('dgd.jpg') %>); height: 400px; width: 100%; position: absolute; top: 0;"></div>
<div class="container" style="padding-top: 100px; position: relative;">
    <h1 class="display-5 fw-bold text-white">Welcome to Evenbrite</h1>
    <p class="col-md-8 fs-4" style="background-color: rgba(0, 0, 0, 0.5); color: bisque;">Here you can find all the latest events from around town.</p>
    <% if user_signed_in? %>
        <%= link_to "Create New Event", new_event_path, class: "btn btn-warning" %>
    <% else %>
        <%= link_to "Register", new_user_registration_path, class: "btn btn-warning" %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary" %>
    <% end %>
</div>

<p style="color: green"><%= notice %></p>


<div class="container" style="padding-top: 100px;">
  <div id="events" class="row">
    <% @events.each do |event| %>
      <div class="col-md-3 col-xl-3">
        <div class="card bg-c-<%= ['yellow', 'pink', 'blue', 'green'].sample %> order-card m-2">
         <%= render event %>
          <%= link_to "Show this event", event, class: "btn btn-outline-none" %>
        </div>
     </div>
   <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-4">
  <div class="row">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <h2><%= @event.title %></h2>
        <div class="d-flex align-items-center" style="gap: 4%;">
        <% if current_user == @event.user %>
          <%= link_to "Edit", edit_event_path(@event), class: "btn btn-warning" %>
          <%= button_to "Destroy this event", @event, method: :delete, class: "btn btn-secondary"%>
        <% end %>
        </div>
      </div>

      <%= render @event %>

</div>
</div>
</div>