config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :attendances
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
    validates :user, presence: true
    validates :event, presence: true
    after_create :new_guest_send

    def new_guest_send
        UserMailer.new_guest_email(self).deliver_now
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy!

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:stripe_customer_id)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_attendance.html.erb
<div id="<%= dom_id attendance %>">
  <p>
    <strong>Stripe customer:</strong>
    <%= attendance.stripe_customer_id %>
  </p>

</div>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stripe_customer_id, style: "display: block" %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Show this attendance", @attendance %> |
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendances</h1>

<div id="attendances">
  <% @attendances.each do |attendance| %>
    <%= render attendance %>
    <p>
      <%= link_to "Show this attendance", attendance %>
    </p>
  <% end %>
</div>

<%= link_to "New attendance", new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendance %>

<div>
  <%= link_to "Edit this attendance", edit_attendance_path(@attendance) %> |
  <%= link_to "Back to attendances", attendances_path %>

  <%= button_to "Destroy this attendance", @attendance, method: :delete %>
</div>