config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :attendances
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evenbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css', media: 'all' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js', integrity: 'sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM', crossorigin: 'anonymous' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css', media: 'all' %>
    <style>
.order-card {
 color: #fff;
}
.bg-c-blue {
 background: linear-gradient(45deg,#4099ff,#73b4ff);
}
.bg-c-green {
 background: linear-gradient(45deg,#2ed8b6,#59e0c5);
}
.bg-c-yellow {
 background: linear-gradient(45deg,#FFB64D,#ffcb80);
}
.bg-c-pink {
 background: linear-gradient(45deg,#FF5370,#ff869a);
}
.card {
 border-radius: 5px;
 -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
 box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
 border: none;
 margin-bottom: 30px;
 -webkit-transition: all 0.3s ease-in-out;
 transition: all 0.3s ease-in-out;
}
.card .card-block {
 padding: 25px;
}
.order-card i {
 font-size: 26px;
}
.f-left {
 float: left;
}
.f-right {
 float: right;
}
</style>
  </head>

  <body data-turbo="false">
    <nav class="navbar navbar-expand-xl navbar-dark" style="z-index: 3; background-color: rgba(0, 0, 0, 0.5); ">
      <div class="container-fluid">
        <a href="/" class="navbar-brand">Evenbrite</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
         <div class="nav-link"> Voici ton email : <%= current_user.email %></div>
        </li>
        <% end %>
          <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          <% else %>
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
          <%= form_tag(destroy_user_session_path, method: :delete) do %>
            <%= submit_tag "Logout", class: "btn btn-outline-light" %>
          <% end %>
                    <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light" %>
          <% end %>
        </li>        
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
  </html>